### ISSUE TITLE
package dependency conflict on pip install -r requirements for abacura 0.0.12

### ISSUE THREAD

**Issue by vajraccedika** [perlsaiyan/abacura#64]
INFO: pip is looking at multiple versions of abacura to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 9) and textual~=0.29.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested textual~=0.29.0
    abacura 0.0.12 depends on textual~=0.28.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by perlsaiyan** [comment]
Changed abacura reqs to >= 0.28.0
